# Generated by Django 4.2.2 on 2023-06-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=200, unique=True)),
                ('telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Familia', 'Familia '), ('Civiles', 'Civiles '), ('Laborales', 'Laborales '), ('Penal antiguo', 'Penal antiguo '), ('Por definir', 'Por definir')], max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_causa', models.CharField(max_length=50)),
                ('horarios', models.IntegerField()),
                ('tramites', models.IntegerField()),
                ('total', models.IntegerField()),
                ('Abogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.abogado')),
            ],
        ),
    ]
